import { db } from '@/lib/db'

async function seedRichMaritimeData() {
  console.log('🌍 Seeding Enhanced Global Maritime & Freight Database...\n')

  // ============================
  // PORTS (25 major global ports - enriched)
  // ============================
  const portsData = [
    { name: 'Shanghai', countryCode: 'CN', region: 'East Asia', latitude: 31.2304, longitude: 121.4737, unlocode: 'CNSHA', portType: 'Seaport', harborSize: 'Very Large', depth: 16.5, cargoTypes: 'Container, Bulk, Liquid', tidalRange: 3.0, timezone: 'Asia/Shanghai', population: 24870000, totalArea: 6340.5, annualTEU: 47000000, annualDWT: 750000000, maxVesselDWT: 400000, berthCount: 620, craneCount: 850, pilotage: 'Compulsory', tugsAvailable: 120, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 2500000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Medium', avgWaitHours: 18, avgStayHours: 48, owner: 'Shanghai International Port Group', operator: 'SIPG', website: 'www.portshanghai.com.cn' },
    { name: 'Singapore', countryCode: 'SG', region: 'Southeast Asia', latitude: 1.3521, longitude: 103.8198, unlocode: 'SGSIN', portType: 'Seaport', harborSize: 'Very Large', depth: 22.0, cargoTypes: 'Container, Bunkering, Liquid', tidalRange: 2.5, timezone: 'Asia/Singapore', population: 5850000, totalArea: 733.1, annualTEU: 39500000, annualDWT: 620000000, maxVesselDWT: 350000, berthCount: 210, craneCount: 310, pilotage: 'Compulsory', tugsAvailable: 85, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1800000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 8, avgStayHours: 24, owner: 'PSA International', operator: 'PSA Singapore', website: 'www.portofsingapore.com' },
    { name: 'Rotterdam', countryCode: 'NL', region: 'North Europe', latitude: 51.9244, longitude: 4.4777, unlocode: 'NLRTM', portType: 'Seaport', harborSize: 'Very Large', depth: 24.0, cargoTypes: 'Container, Bulk, Ro-Ro, Liquid', tidalRange: 1.8, timezone: 'Europe/Amsterdam', population: 654000, totalArea: 324.1, annualTEU: 14700000, annualDWT: 470000000, maxVesselDWT: 250000, berthCount: 175, craneCount: 230, pilotage: 'Compulsory', tugsAvailable: 45, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 3200000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 6, avgStayHours: 36, owner: 'Port of Rotterdam Authority', operator: 'Port of Rotterdam N.V.', website: 'www.portofrotterdam.com' },
    { name: 'Busan', countryCode: 'KR', region: 'East Asia', latitude: 35.1796, longitude: 129.0756, unlocode: 'KRPUS', portType: 'Seaport', harborSize: 'Very Large', depth: 17.0, cargoTypes: 'Container, Bulk, Liquid', tidalRange: 1.2, timezone: 'Asia/Seoul', population: 3400000, totalArea: 770.4, annualTEU: 23200000, annualDWT: 310000000, maxVesselDWT: 220000, berthCount: 145, craneCount: 180, pilotage: 'Compulsory', tugsAvailable: 55, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1400000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 10, avgStayHours: 30, owner: 'Busan Port Authority', operator: 'Busan Port Authority', website: 'www.busanpa.com' },
    { name: 'Ningbo-Zhoushan', countryCode: 'CN', region: 'East Asia', latitude: 29.8683, longitude: 121.5440, unlocode: 'CNNGB', portType: 'Seaport', harborSize: 'Very Large', depth: 18.0, cargoTypes: 'Container, Bulk, Liquid', tidalRange: 3.5, timezone: 'Asia/Shanghai', population: 9400000, totalArea: 9816.0, annualTEU: 35300000, annualDWT: 1200000000, maxVesselDWT: 400000, berthCount: 680, craneCount: 920, pilotage: 'Compulsory', tugsAvailable: 110, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 2800000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Medium', avgWaitHours: 16, avgStayHours: 42, owner: 'Ningbo Zhoushan Port Group', operator: 'NZP Group', website: 'www.nbport.com.cn' },
    { name: 'Qingdao', countryCode: 'CN', region: 'East Asia', latitude: 36.0671, longitude: 120.3826, unlocode: 'CNTAO', portType: 'Seaport', harborSize: 'Large', depth: 17.5, cargoTypes: 'Container, Bulk, Liquid', tidalRange: 4.0, timezone: 'Asia/Shanghai', population: 10300000, totalArea: 11293.0, annualTEU: 26500000, annualDWT: 580000000, maxVesselDWT: 300000, berthCount: 175, craneCount: 240, pilotage: 'Compulsory', tugsAvailable: 65, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1600000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 12, avgStayHours: 30, owner: 'Qingdao Port Group', operator: 'Qingdao Port Co.', website: 'www.qdport.com' },
    { name: 'Guangzhou', countryCode: 'CN', region: 'East Asia', latitude: 23.1291, longitude: 113.2644, unlocode: 'CNGZG', portType: 'Seaport', harborSize: 'Very Large', depth: 15.0, cargoTypes: 'Container, Bulk, General', tidalRange: 2.0, timezone: 'Asia/Shanghai', population: 18700000, totalArea: 7434.4, annualTEU: 24200000, annualDWT: 420000000, maxVesselDWT: 180000, berthCount: 360, craneCount: 480, pilotage: 'Compulsory', tugsAvailable: 75, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 2000000, coldStorage: true, hazardousHandling: 'Class 1-9', congestionLevel: 'Medium', avgWaitHours: 20, avgStayHours: 40, owner: 'Guangzhou Port Authority', operator: 'Guangzhou Port Group', website: 'www.gzport.com' },
    { name: 'Tianjin', countryCode: 'CN', region: 'East Asia', latitude: 39.3434, longitude: 117.3616, unlocode: 'CNTSN', portType: 'Seaport', harborSize: 'Very Large', depth: 18.0, cargoTypes: 'Container, Bulk, Liquid', tidalRange: 3.0, timezone: 'Asia/Shanghai', population: 13900000, totalArea: 11966.0, annualTEU: 21000000, annualDWT: 510000000, maxVesselDWT: 300000, berthCount: 195, craneCount: 260, pilotage: 'Compulsory', tugsAvailable: 60, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1500000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 14, avgStayHours: 36, owner: 'Tianjin Port Group', operator: 'Tianjin Port Holdings', website: 'www.ptacn.com' },
    { name: 'Hamburg', countryCode: 'DE', region: 'North Europe', latitude: 53.5511, longitude: 9.9937, unlocode: 'DEHAM', portType: 'Seaport', harborSize: 'Very Large', depth: 16.5, cargoTypes: 'Container, Bulk, Ro-Ro', tidalRange: 3.6, timezone: 'Europe/Berlin', population: 1850000, totalArea: 755.2, annualTEU: 8700000, annualDWT: 130000000, maxVesselDWT: 200000, berthCount: 320, craneCount: 290, pilotage: 'Compulsory', tugsAvailable: 30, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 2200000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 8, avgStayHours: 24, owner: 'Hamburg Port Authority', operator: 'Hamburger Hafen und Logistik AG', website: 'www.hamburg-port.de' },
    { name: 'Antwerp', countryCode: 'BE', region: 'North Europe', latitude: 51.2602, longitude: 4.4026, unlocode: 'BEANR', portType: 'Seaport', harborSize: 'Large', depth: 18.0, cargoTypes: 'Container, Bulk, Liquid, Ro-Ro', tidalRange: 5.0, timezone: 'Europe/Brussels', population: 520000, totalArea: 204.5, annualTEU: 13500000, annualDWT: 200000000, maxVesselDWT: 200000, berthCount: 165, craneCount: 200, pilotage: 'Compulsory', tugsAvailable: 25, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1800000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 10, avgStayHours: 30, owner: 'Antwerp Port Authority', operator: 'Port of Antwerp-Bruges', website: 'www.portofantwerp.com' },
    { name: 'Los Angeles', countryCode: 'US', region: 'North America', latitude: 33.9425, longitude: -118.4081, unlocode: 'USLAX', portType: 'Seaport', harborSize: 'Very Large', depth: 18.0, cargoTypes: 'Container, Auto, Break Bulk', tidalRange: 1.8, timezone: 'America/Los_Angeles', population: 3970000, totalArea: 1302.0, annualTEU: 9380000, annualDWT: 180000000, maxVesselDWT: 220000, berthCount: 85, craneCount: 95, pilotage: 'Compulsory', tugsAvailable: 20, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1200000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'High', avgWaitHours: 36, avgStayHours: 72, owner: 'City of Los Angeles', operator: 'Port of Los Angeles', website: 'www.portla.org' },
    { name: 'Long Beach', countryCode: 'US', region: 'North America', latitude: 33.7884, longitude: -118.1840, unlocode: 'USLGB', portType: 'Seaport', harborSize: 'Very Large', depth: 20.0, cargoTypes: 'Container, Bulk, Auto', tidalRange: 1.5, timezone: 'America/Los_Angeles', population: 470000, totalArea: 330.8, annualTEU: 8070000, annualDWT: 150000000, maxVesselDWT: 240000, berthCount: 80, craneCount: 85, pilotage: 'Compulsory', tugsAvailable: 18, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1000000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'High', avgWaitHours: 32, avgStayHours: 65, owner: 'City of Long Beach', operator: 'Port of Long Beach', website: 'www.polb.com' },
    { name: 'Dubai (Jebel Ali)', countryCode: 'AE', region: 'Middle East', latitude: 25.0208, longitude: 55.1441, unlocode: 'AEDXB', portType: 'Seaport', harborSize: 'Very Large', depth: 17.0, cargoTypes: 'Container, Bulk, General', tidalRange: 1.2, timezone: 'Asia/Dubai', population: 3550000, totalArea: 4114.0, annualTEU: 14500000, annualDWT: 280000000, maxVesselDWT: 250000, berthCount: 110, craneCount: 140, pilotage: 'Compulsory', tugsAvailable: 35, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1900000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 12, avgStayHours: 28, owner: 'DP World', operator: 'DP World UAE', website: 'www.jafza.ae' },
    { name: 'Jeddah', countryCode: 'SA', region: 'Middle East', latitude: 21.4858, longitude: 39.1925, unlocode: 'SAJED', portType: 'Seaport', harborSize: 'Large', depth: 16.0, cargoTypes: 'Container, Bulk, Liquid', tidalRange: 0.6, timezone: 'Asia/Riyadh', population: 4700000, totalArea: 1600.0, annualTEU: 5200000, annualDWT: 120000000, maxVesselDWT: 200000, berthCount: 63, craneCount: 75, pilotage: 'Compulsory', tugsAvailable: 22, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 800000, coldStorage: true, hazardousHandling: 'Class 1-9', congestionLevel: 'Low', avgWaitHours: 10, avgStayHours: 24, owner: 'Saudi Ports Authority', operator: 'Mawani', website: 'www.mawani.gov.sa' },
    { name: 'Mumbai', countryCode: 'IN', region: 'South Asia', latitude: 19.0760, longitude: 72.8777, unlocode: 'INBOM', portType: 'Seaport', harborSize: 'Large', depth: 14.0, cargoTypes: 'Container, Bulk, Liquid, General', tidalRange: 3.5, timezone: 'Asia/Kolkata', population: 20600000, totalArea: 603.4, annualTEU: 6100000, annualDWT: 140000000, maxVesselDWT: 125000, berthCount: 55, craneCount: 65, pilotage: 'Compulsory', tugsAvailable: 30, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 900000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'High', avgWaitHours: 28, avgStayHours: 48, owner: 'Mumbai Port Trust', operator: 'MbPT', website: 'www.mumbaiport.gov.in' },
    { name: 'Felixstowe', countryCode: 'GB', region: 'North Europe', latitude: 51.9497, longitude: 1.3506, unlocode: 'GBFXT', portType: 'Seaport', harborSize: 'Large', depth: 16.0, cargoTypes: 'Container, Ro-Ro', tidalRange: 3.8, timezone: 'Europe/London', population: 24000, totalArea: 19.1, annualTEU: 4200000, annualDWT: 52000000, maxVesselDWT: 200000, berthCount: 32, craneCount: 50, pilotage: 'Compulsory', tugsAvailable: 12, bunkering: true, freshWater: true, medicalFacility: false, repairFacility: true, warehouseSpace: 400000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Medium', avgWaitHours: 14, avgStayHours: 18, owner: 'Associated British Ports', operator: 'ABP Felixstowe', website: 'www.abports.co.uk' },
    { name: 'Tokyo', countryCode: 'JP', region: 'East Asia', latitude: 35.6762, longitude: 139.6503, unlocode: 'JPTYO', portType: 'Seaport', harborSize: 'Large', depth: 15.0, cargoTypes: 'Container, Bulk, General', tidalRange: 1.8, timezone: 'Asia/Tokyo', population: 13960000, totalArea: 2194.0, annualTEU: 5000000, annualDWT: 90000000, maxVesselDWT: 120000, berthCount: 185, craneCount: 120, pilotage: 'Compulsory', tugsAvailable: 40, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 1100000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 8, avgStayHours: 20, owner: 'Tokyo Metropolitan Government', operator: 'Tokyo Port Authority', website: 'www.portoftokyo.or.jp' },
    { name: 'Yokohama', countryCode: 'JP', region: 'East Asia', latitude: 35.4437, longitude: 139.6380, unlocode: 'JPYOK', portType: 'Seaport', harborSize: 'Large', depth: 16.0, cargoTypes: 'Container, Ro-Ro, General', tidalRange: 1.6, timezone: 'Asia/Tokyo', population: 3760000, totalArea: 437.6, annualTEU: 2800000, annualDWT: 65000000, maxVesselDWT: 140000, berthCount: 95, craneCount: 85, pilotage: 'Compulsory', tugsAvailable: 28, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 700000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 6, avgStayHours: 18, owner: 'City of Yokohama', operator: 'Yokohama Port Authority', website: 'www.city.yokohama.jp' },
    { name: 'Suez Canal', countryCode: 'EG', region: 'Africa', latitude: 30.5876, longitude: 32.2720, unlocode: 'EGSUZ', portType: 'Canal', harborSize: 'Large', depth: 24.0, cargoTypes: 'Transit, Container, Bulk', tidalRange: 0.7, timezone: 'Africa/Cairo', population: 56000, totalArea: 1000.0, annualTEU: 0, annualDWT: 1200000000, maxVesselDWT: 400000, berthCount: 15, craneCount: 8, pilotage: 'Compulsory', tugsAvailable: 40, bunkering: false, freshWater: false, medicalFacility: true, repairFacility: true, warehouseSpace: 100000, coldStorage: false, hazardousHandling: 'Class 1-9', congestionLevel: 'Medium', avgWaitHours: 48, avgStayHours: 18, owner: 'Suez Canal Authority', operator: 'SCA', website: 'www.suezcanal.gov.eg' },
    { name: 'Piraeus', countryCode: 'GR', region: 'Mediterranean', latitude: 37.9379, longitude: 23.6473, unlocode: 'GRPIR', portType: 'Seaport', harborSize: 'Large', depth: 16.0, cargoTypes: 'Container, Ro-Ro, General', tidalRange: 0.1, timezone: 'Europe/Athens', population: 660000, totalArea: 10.9, annualTEU: 4700000, annualDWT: 85000000, maxVesselDWT: 200000, berthCount: 42, craneCount: 55, pilotage: 'Compulsory', tugsAvailable: 15, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 500000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 8, avgStayHours: 22, owner: 'Piraeus Port Authority', operator: 'OLP (Cosco)', website: 'www.ppa.gr' },
    { name: 'Rio de Janeiro', countryCode: 'BR', region: 'South America', latitude: -22.9068, longitude: -43.1729, unlocode: 'BRRIO', portType: 'Seaport', harborSize: 'Large', depth: 15.5, cargoTypes: 'Container, Bulk, Liquid, General', tidalRange: 1.2, timezone: 'America/Sao_Paulo', population: 6750000, totalArea: 1221.0, annualTEU: 1200000, annualDWT: 85000000, maxVesselDWT: 180000, berthCount: 45, craneCount: 35, pilotage: 'Compulsory', tugsAvailable: 15, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 400000, coldStorage: true, hazardousHandling: 'Class 1-9', congestionLevel: 'Medium', avgWaitHours: 16, avgStayHours: 36, owner: 'Companhia Docas do Rio de Janeiro', operator: 'CDRJ', website: 'www.portodoriocom.br' },
    { name: 'Sydney', countryCode: 'AU', region: 'Oceania', latitude: -33.8688, longitude: 151.2093, unlocode: 'AUSYD', portType: 'Seaport', harborSize: 'Medium', depth: 14.0, cargoTypes: 'Container, Bulk, General', tidalRange: 1.8, timezone: 'Australia/Sydney', population: 5300000, totalArea: 12368.0, annualTEU: 2900000, annualDWT: 45000000, maxVesselDWT: 80000, berthCount: 38, craneCount: 28, pilotage: 'Compulsory', tugsAvailable: 12, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 350000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 8, avgStayHours: 20, owner: 'NSW Ports', operator: 'Sydney Ports', website: 'www.nswports.com' },
    { name: 'Mombasa', countryCode: 'KE', region: 'East Africa', latitude: -4.0435, longitude: 39.6682, unlocode: 'KEMBA', portType: 'Seaport', harborSize: 'Medium', depth: 13.0, cargoTypes: 'Container, Bulk, Liquid', tidalRange: 3.2, timezone: 'Africa/Nairobi', population: 1200000, totalArea: 230.0, annualTEU: 1400000, annualDWT: 22000000, maxVesselDWT: 65000, berthCount: 21, craneCount: 16, pilotage: 'Compulsory', tugsAvailable: 6, bunkering: true, freshWater: true, medicalFacility: false, repairFacility: false, warehouseSpace: 200000, coldStorage: true, hazardousHandling: 'Class 1-6', congestionLevel: 'Medium', avgWaitHours: 24, avgStayHours: 48, owner: 'Kenya Ports Authority', operator: 'KPA', website: 'www.kpa.co.ke' },
    { name: 'Lagos', countryCode: 'NG', region: 'West Africa', latitude: 6.5244, longitude: 3.3792, unlocode: 'NGLOS', portType: 'Seaport', harborSize: 'Medium', depth: 13.5, cargoTypes: 'Container, Bulk, Liquid', tidalRange: 1.2, timezone: 'Africa/Lagos', population: 15600000, totalArea: 1171.0, annualTEU: 1200000, annualDWT: 25000000, maxVesselDWT: 60000, berthCount: 18, craneCount: 14, pilotage: 'Compulsory', tugsAvailable: 8, bunkering: true, freshWater: true, medicalFacility: false, repairFacility: false, warehouseSpace: 150000, coldStorage: false, hazardousHandling: 'Class 1-5', congestionLevel: 'High', avgWaitHours: 48, avgStayHours: 72, owner: 'Nigerian Ports Authority', operator: 'NPA', website: 'www.npa.gov.ng' },
    { name: 'Colombo', countryCode: 'LK', region: 'South Asia', latitude: 6.9271, longitude: 79.8612, unlocode: 'LKCMB', portType: 'Seaport', harborSize: 'Large', depth: 20.0, cargoTypes: 'Container, Bulk, Transshipment', tidalRange: 0.8, timezone: 'Asia/Colombo', population: 750000, totalArea: 37.3, annualTEU: 7800000, annualDWT: 110000000, maxVesselDWT: 240000, berthCount: 22, craneCount: 30, pilotage: 'Compulsory', tugsAvailable: 10, bunkering: true, freshWater: true, medicalFacility: true, repairFacility: true, warehouseSpace: 350000, coldStorage: true, hazardousHandling: 'Full IMDG', congestionLevel: 'Low', avgWaitHours: 10, avgStayHours: 22, owner: 'Sri Lanka Ports Authority', operator: 'SLPA', website: 'www.slpa.lk' },
  ]

  console.log(`🚢 Creating ${portsData.length} enriched global ports...`)
  const ports = await Promise.all(portsData.map((p) => db.port.create({ data: p })))

  // ============================
  // VESSELS (15 vessels - enriched)
  // ============================
  const vesselsData = [
    { mmsi: 477394500, imo: 9547843, name: 'Pacific Fortune', callSign: 'VRBZ8', vesselType: 'Container Ship', flagCountry: 'HK', grossTonnage: 54236, deadweight: 69784, length: 299.9, breadth: 40.3, draft: 14.0, yearBuilt: 2012, status: 'Active', latitude: 22.28, longitude: 114.17, speed: 14.2, heading: 265, destination: 'SGSIN', eta: new Date(Date.now() + 4 * 86400000), classificationSociety: "Lloyd's Register", vesselClass: 'Post-Panamax', iceClass: 'None', engineType: 'Diesel', enginePower: 57600, maxSpeed: 24.5, fuelCapacity: 7200, fuelType: 'VLSFO', teuCapacity: 5100, reeferPoints: 400, cargoHoldCount: 8, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 28, shipManager: 'V Ships Hong Kong', registeredOwner: 'Pacific Fortune Maritime Ltd', beneficialOwner: 'CMA CGM Group', insurancePandI: 'Britannia P&I', imoCertExpiry: new Date('2027-06-15'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'C', totalVoyages: 342, totalDistanceNm: 890000, ownerCountry: 'HK' },
    { mmsi: 636091537, imo: 9458054, name: 'MV Atlantic Star', callSign: 'D5IQ4', vesselType: 'Bulk Carrier', flagCountry: 'LR', grossTonnage: 38542, deadweight: 72398, length: 225.0, breadth: 32.3, draft: 14.2, yearBuilt: 2010, status: 'Active', latitude: 34.05, longitude: -20.12, speed: 11.8, heading: 45, destination: 'NLRTM', eta: new Date(Date.now() + 8 * 86400000), classificationSociety: 'DNV GL', vesselClass: 'Handymax', iceClass: 'ICE-1C', engineType: 'Diesel', enginePower: 9480, maxSpeed: 15.0, fuelCapacity: 3400, fuelType: 'VLSFO', teuCapacity: 0, reeferPoints: 0, cargoHoldCount: 5, craneCount: 4, doubleHull: true, bulbousBow: true, crewCapacity: 24, shipManager: 'Bernhard Schulte Shipmanagement', registeredOwner: 'Atlantic Bulk Carriers Inc', beneficialOwner: 'Oldendorff Carriers', insurancePandI: 'North of England P&I', imoCertExpiry: new Date('2027-09-30'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'D', totalVoyages: 215, totalDistanceNm: 520000, ownerCountry: 'LR' },
    { mmsi: 311045300, imo: 9468930, name: 'CMA CGM Marco Polo', callSign: 'C6YB5', vesselType: 'Container Ship', flagCountry: 'PA', grossTonnage: 156278, deadweight: 187625, length: 396.0, breadth: 53.6, draft: 16.0, yearBuilt: 2013, status: 'Active', latitude: 51.92, longitude: 4.48, speed: 16.5, heading: 210, destination: 'SGSIN', eta: new Date(Date.now() + 18 * 86400000), classificationSociety: 'Bureau Veritas', vesselClass: 'ULCS', iceClass: 'None', engineType: 'Diesel', enginePower: 80000, maxSpeed: 24.0, fuelCapacity: 13800, fuelType: 'VLSFO', teuCapacity: 16020, reeferPoints: 800, cargoHoldCount: 12, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 35, shipManager: 'CMA Ships', registeredOwner: 'CMA CGM S.A.', beneficialOwner: 'Rodolphe Saadé', insurancePandI: 'Skuld P&I', imoCertExpiry: new Date('2028-03-20'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'B', totalVoyages: 180, totalDistanceNm: 750000, ownerCountry: 'FR' },
    { mmsi: 353136000, imo: 9654763, name: 'Ever Given', callSign: 'H3RC', vesselType: 'Container Ship', flagCountry: 'PA', grossTonnage: 199293, deadweight: 224965, length: 400.0, breadth: 59.0, draft: 16.0, yearBuilt: 2018, status: 'Active', latitude: 31.25, longitude: 32.30, speed: 12.0, heading: 175, destination: 'NLRTM', eta: new Date(Date.now() + 12 * 86400000), classificationSociety: 'American Bureau of Shipping', vesselClass: 'ULCS', iceClass: 'None', engineType: 'Diesel', enginePower: 72000, maxSpeed: 22.8, fuelCapacity: 15000, fuelType: 'VLSFO', teuCapacity: 20124, reeferPoints: 1000, cargoHoldCount: 14, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 35, shipManager: 'Evergreen Marine Corp', registeredOwner: 'Evergreen Marine Corp', beneficialOwner: 'Chang Yung-fa Foundation', insurancePandI: 'Britannia P&I', imoCertExpiry: new Date('2030-07-10'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'B', totalVoyages: 95, totalDistanceNm: 380000, ownerCountry: 'TW' },
    { mmsi: 538008212, imo: 9838944, name: 'MSC Gulsun', callSign: 'V7HF2', vesselType: 'Container Ship', flagCountry: 'PA', grossTonnage: 232170, deadweight: 257598, length: 400.0, breadth: 61.5, draft: 16.5, yearBuilt: 2019, status: 'Active', latitude: 1.35, longitude: 104.10, speed: 18.2, heading: 30, destination: 'CNSHA', eta: new Date(Date.now() + 5 * 86400000), classificationSociety: 'DNV GL', vesselClass: 'Mega', iceClass: 'None', engineType: 'LNG Dual-Fuel', enginePower: 82000, maxSpeed: 22.0, fuelCapacity: 16500, fuelType: 'LNG', teuCapacity: 23756, reeferPoints: 1200, cargoHoldCount: 15, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 38, shipManager: 'MSC Ship Management Ltd', registeredOwner: 'MSC Mediterranean Shipping Co', beneficialOwner: 'Gianluigi Aponte', insurancePandI: 'London P&I', imoCertExpiry: new Date('2031-05-15'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'A', totalVoyages: 68, totalDistanceNm: 210000, ownerCountry: 'CH' },
    { mmsi: 563005500, imo: 9786412, name: 'Cosco Shipping Universe', callSign: '9HDV8', vesselType: 'Container Ship', flagCountry: 'HK', grossTonnage: 199890, deadweight: 223413, length: 400.0, breadth: 58.6, draft: 16.0, yearBuilt: 2018, status: 'Active', latitude: -33.87, longitude: 151.20, speed: 15.5, heading: 340, destination: 'CNSHA', eta: new Date(Date.now() + 10 * 86400000), classificationSociety: 'DNV GL', vesselClass: 'ULCS', iceClass: 'None', engineType: 'Diesel', enginePower: 69920, maxSpeed: 22.5, fuelCapacity: 14200, fuelType: 'VLSFO', teuCapacity: 21200, reeferPoints: 1050, cargoHoldCount: 14, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 36, shipManager: 'Cosco Shipping Manning', registeredOwner: 'Cosco Shipping Lines Co', beneficialOwner: 'COSCO Shipping', insurancePandI: 'North Standard P&I', imoCertExpiry: new Date('2030-09-01'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'B', totalVoyages: 72, totalDistanceNm: 240000, ownerCountry: 'CN' },
    { mmsi: 431502900, imo: 9764523, name: 'ONE Harmony', callSign: '7JFJ', vesselType: 'Container Ship', flagCountry: 'JP', grossTonnage: 152660, deadweight: 152888, length: 364.0, breadth: 51.0, draft: 14.5, yearBuilt: 2017, status: 'Active', latitude: 35.44, longitude: 139.64, speed: 13.8, heading: 90, destination: 'USLAX', eta: new Date(Date.now() + 12 * 86400000), classificationSociety: "ClassNK", vesselClass: 'Post-Panamax', iceClass: 'None', engineType: 'Diesel', enginePower: 56000, maxSpeed: 24.0, fuelCapacity: 9500, fuelType: 'VLSFO', teuCapacity: 14000, reeferPoints: 700, cargoHoldCount: 10, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 30, shipManager: 'MONA Ship Management', registeredOwner: 'ONE (Ocean Network Express)', beneficialOwner: 'ONE Consortium', insurancePandI: 'Japan P&I Club', imoCertExpiry: new Date('2029-12-01'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'B', totalVoyages: 145, totalDistanceNm: 480000, ownerCountry: 'JP' },
    { mmsi: 305753000, imo: 9457058, name: 'Oil Tanker Aegean', callSign: 'V4BX2', vesselType: 'Tanker', flagCountry: 'MT', grossTonnage: 82156, deadweight: 114946, length: 274.2, breadth: 48.0, draft: 17.0, yearBuilt: 2011, status: 'Active', latitude: 25.02, longitude: 55.14, speed: 10.5, heading: 320, destination: 'SAJED', eta: new Date(Date.now() + 2 * 86400000), classificationSociety: 'RINA', vesselClass: 'Suezmax', iceClass: 'None', engineType: 'Diesel', enginePower: 10480, maxSpeed: 15.5, fuelCapacity: 5500, fuelType: 'VLSFO', teuCapacity: 0, reeferPoints: 0, cargoHoldCount: 12, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 30, shipManager: 'V Ships Oil', registeredOwner: 'Aegean Shipping Enterprises', beneficialOwner: 'John Angelicoussis', insurancePandI: 'Standard P&I', imoCertExpiry: new Date('2027-08-22'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'C', totalVoyages: 198, totalDistanceNm: 560000, ownerCountry: 'MT' },
    { mmsi: 248762000, imo: 9397136, name: 'MV Nordic Spirit', callSign: '9HA4528', vesselType: 'Ro-Ro Ship', flagCountry: 'NO', grossTonnage: 61234, deadweight: 18675, length: 231.0, breadth: 32.0, draft: 7.5, yearBuilt: 2008, status: 'Active', latitude: 53.55, longitude: 9.99, speed: 16.0, heading: 180, destination: 'GBFXT', eta: new Date(Date.now() + 1 * 86400000), classificationSociety: 'DNV GL', vesselClass: 'PCTC', iceClass: 'ICE-1A', engineType: 'Diesel', enginePower: 18000, maxSpeed: 21.0, fuelCapacity: 3200, fuelType: 'VLSFO', teuCapacity: 0, reeferPoints: 0, cargoHoldCount: 6, craneCount: 0, doubleHull: true, bulbousBow: false, crewCapacity: 22, passengers: 12, shipManager: 'Wallenius Wilhelmsen', registeredOwner: 'Wallenius Lines', beneficialOwner: 'WW Group', insurancePandI: 'Skuld P&I', imoCertExpiry: new Date('2028-11-15'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'B', totalVoyages: 280, totalDistanceNm: 620000, ownerCountry: 'NO' },
    { mmsi: 477765400, imo: 9745387, name: 'Global Mercy', callSign: '3FQK5', vesselType: 'General Cargo', flagCountry: 'LR', grossTonnage: 29410, deadweight: 43120, length: 177.0, breadth: 27.6, draft: 10.5, yearBuilt: 2015, status: 'Active', latitude: -4.04, longitude: 39.67, speed: 9.2, heading: 60, destination: 'INBOM', eta: new Date(Date.now() + 7 * 86400000), classificationSociety: "Lloyd's Register", vesselClass: 'Handysize', iceClass: 'None', engineType: 'Diesel', enginePower: 6800, maxSpeed: 14.0, fuelCapacity: 1800, fuelType: 'VLSFO', teuCapacity: 0, reeferPoints: 0, cargoHoldCount: 4, craneCount: 4, doubleHull: true, bulbousBow: true, crewCapacity: 20, shipManager: 'Bernhard Schulte', registeredOwner: 'Mercy Maritime Ltd', beneficialOwner: 'Mercy Shipping Group', insurancePandI: 'Britannia P&I', imoCertExpiry: new Date('2029-04-30'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'D', totalVoyages: 165, totalDistanceNm: 340000, ownerCountry: 'LR' },
    { mmsi: 235002342, imo: 9525761, name: 'LNG Pioneer', callSign: 'MHJT6', vesselType: 'LNG Carrier', flagCountry: 'GB', grossTonnage: 98347, deadweight: 98523, length: 295.0, breadth: 46.0, draft: 12.5, yearBuilt: 2013, status: 'Active', latitude: 22.28, longitude: 120.30, speed: 17.0, heading: 270, destination: 'JPTYO', eta: new Date(Date.now() + 3 * 86400000), classificationSociety: 'DNV GL', vesselClass: 'Moss Type LNG', iceClass: 'ICE-1A', engineType: 'Steam Turbine', enginePower: 29700, maxSpeed: 20.0, fuelCapacity: 145000, fuelType: 'LNG', teuCapacity: 0, reeferPoints: 0, cargoHoldCount: 4, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 35, shipManager: 'BG LNG Ship Management', registeredOwner: 'BG LNG Ltd', beneficialOwner: 'BP Shipping', insurancePandI: 'Standard P&I', imoCertExpiry: new Date('2028-07-10'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'B', totalVoyages: 110, totalDistanceNm: 420000, ownerCountry: 'GB' },
    { mmsi: 370654000, imo: 9834561, name: 'Hapag-Lloyd Express', callSign: '3FOW7', vesselType: 'Container Ship', flagCountry: 'DE', grossTonnage: 105000, deadweight: 121400, length: 333.0, breadth: 48.0, draft: 15.5, yearBuilt: 2020, status: 'Active', latitude: 37.94, longitude: 23.65, speed: 14.8, heading: 315, destination: 'NLRTM', eta: new Date(Date.now() + 6 * 86400000), classificationSociety: 'DNV GL', vesselClass: 'Post-Panamax', iceClass: 'None', engineType: 'LNG Dual-Fuel', enginePower: 64000, maxSpeed: 23.0, fuelCapacity: 11000, fuelType: 'LNG', teuCapacity: 10500, reeferPoints: 550, cargoHoldCount: 9, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 28, shipManager: 'Hapag-Lloyd Crew Management', registeredOwner: 'Hapag-Lloyd AG', beneficialOwner: 'Hapag-Lloyd AG', insurancePandI: 'Britannia P&I', imoCertExpiry: new Date('2032-01-15'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'A', totalVoyages: 55, totalDistanceNm: 180000, ownerCountry: 'DE' },
    { mmsi: 416001234, imo: 9754321, name: 'Columbia Star', callSign: 'WDFN3', vesselType: 'Bulk Carrier', flagCountry: 'MH', grossTonnage: 42300, deadweight: 82400, length: 229.0, breadth: 32.3, draft: 14.5, yearBuilt: 2016, status: 'In Port', latitude: -22.91, longitude: -43.17, speed: 0, heading: 0, destination: null, eta: null, classificationSociety: 'ClassNK', vesselClass: 'Panamax', iceClass: 'None', engineType: 'Diesel', enginePower: 9240, maxSpeed: 14.5, fuelCapacity: 3100, fuelType: 'VLSFO', teuCapacity: 0, reeferPoints: 0, cargoHoldCount: 7, craneCount: 4, doubleHull: true, bulbousBow: true, crewCapacity: 24, shipManager: 'Star Bulk Management', registeredOwner: 'Star Bulk Carriers', beneficialOwner: 'Petros Pappas', insurancePandI: 'Britannia P&I', imoCertExpiry: new Date('2031-05-20'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'C', totalVoyages: 125, totalDistanceNm: 380000, ownerCountry: 'MH' },
    { mmsi: 636090876, imo: 9501234, name: 'Mauritius Unity', callSign: '5IUP4', vesselType: 'General Cargo', flagCountry: 'MU', grossTonnage: 18700, deadweight: 28500, length: 162.0, breadth: 25.0, draft: 9.8, yearBuilt: 2009, status: 'Active', latitude: -6.16, longitude: 39.19, speed: 11.0, heading: 75, destination: 'KEMBA', eta: new Date(Date.now() + 1 * 86400000), classificationSociety: 'Bureau Veritas', vesselClass: 'Handysize', iceClass: 'None', engineType: 'Diesel', enginePower: 4800, maxSpeed: 13.5, fuelCapacity: 1200, fuelType: 'VLSFO', teuCapacity: 0, reeferPoints: 0, cargoHoldCount: 3, craneCount: 2, doubleHull: true, bulbousBow: false, crewCapacity: 18, shipManager: 'Mauritius Shipping Ltd', registeredOwner: 'Mauritius Shipping Corp', beneficialOwner: 'Government of Mauritius', insurancePandI: 'Standard P&I', imoCertExpiry: new Date('2027-12-31'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'D', totalVoyages: 210, totalDistanceNm: 450000, ownerCountry: 'MU' },
    { mmsi: 352773000, imo: 9678234, name: 'Barcelona Bridge', callSign: '3EKL7', vesselType: 'Container Ship', flagCountry: 'PA', grossTonnage: 85000, deadweight: 100500, length: 336.0, breadth: 48.4, draft: 15.0, yearBuilt: 2016, status: 'Active', latitude: 19.08, longitude: 72.88, speed: 13.2, heading: 270, destination: 'AEDXB', eta: new Date(Date.now() + 5 * 86400000), classificationSociety: "Lloyd's Register", vesselClass: 'Post-Panamax', iceClass: 'None', engineType: 'Diesel', enginePower: 52000, maxSpeed: 24.0, fuelCapacity: 8500, fuelType: 'VLSFO', teuCapacity: 8500, reeferPoints: 450, cargoHoldCount: 8, craneCount: 0, doubleHull: true, bulbousBow: true, crewCapacity: 26, shipManager: 'Zodiac Maritime', registeredOwner: 'Costamare Shipping', beneficialOwner: 'Costamare Inc', insurancePandI: 'Britannia P&I', imoCertExpiry: new Date('2030-08-15'), solasCompliant: true, marpolCompliant: true, ballastWater: 'BWMS Treatment', emissionRating: 'C', totalVoyages: 130, totalDistanceNm: 410000, ownerCountry: 'GR' },
  ]

  console.log(`⚓ Creating ${vesselsData.length} enriched vessels...`)
  const vessels = await Promise.all(vesselsData.map((v) => db.vessel.create({ data: { ...v, lastPosition: new Date() } })))

  // ============================
  // SHIPMENTS (10 shipments - enriched)
  // ============================
  const now = Date.now()
  const shipmentsData = [
    { billOfLading: 'MAEU2026072001', bookingRef: 'BK-SHA-001', status: 'In Transit', cargoType: 'Electronics', cargoWeight: 24500, cargoValue: 4850000, cargoDesc: 'Consumer electronics and semiconductors', hsCode: '8542', vesselId: vessels[0].id, originPortId: ports[0].id, destPortId: ports[1].id, departureDate: new Date(now - 3 * 86400000), etd: new Date(now - 3 * 86400000), eta: new Date(now + 4 * 86400000), transitDays: 7, freightCost: 28500, currency: 'USD', shipper: 'Shanghai Tech Industries', consignee: 'Singapore Electronics Pte', notifyParty: 'Singapore Electronics Pte', forwarder: 'Kuehne + Nagel', agent: 'CTK Customs Singapore', incoterms: 'CIF', paymentTerms: 'L/C at sight', freightTerms: 'Prepaid', containerCount: 18, totalTEU: 28, totalFEU: 5, weightUnit: 'KG', volumeCbm: 85, dangerousGoods: false, customsStatus: 'Cleared', customsRef: 'SG-2026-78432', clearedAt: new Date(now - 2 * 86400000), priority: 'Express', serviceLevel: 'FCL', insurancePolicy: 'MAR-2026-4521', insuranceValue: 5000000, remarks: 'Priority shipment - customer electronics launch' },
    { billOfLading: 'MSCU2026071802', bookingRef: 'BK-RTM-002', status: 'In Transit', cargoType: 'Machinery', cargoWeight: 58000, cargoValue: 12400000, cargoDesc: 'Industrial machinery and turbine parts', hsCode: '8412', vesselId: vessels[2].id, originPortId: ports[2].id, destPortId: ports[1].id, departureDate: new Date(now - 5 * 86400000), etd: new Date(now - 5 * 86400000), eta: new Date(now + 13 * 86400000), transitDays: 18, freightCost: 62000, currency: 'USD', shipper: 'Dutch Machinery BV', consignee: 'Pacific Industrial Co.', notifyParty: 'Pacific Industrial Co.', forwarder: 'MSC Agency', agent: 'Customs Broker Singapore', incoterms: 'FOB', paymentTerms: 'Net 30', freightTerms: 'Collect', containerCount: 32, totalTEU: 48, totalFEU: 8, weightUnit: 'KG', volumeCbm: 210, dangerousGoods: false, customsStatus: 'Cleared', customsRef: 'NL-2026-34512', clearedAt: new Date(now - 4 * 86400000), priority: 'Standard', serviceLevel: 'FCL', insurancePolicy: 'HULL-2026-7821', insuranceValue: 13000000, remarks: 'Heavy lift - requires crane at destination' },
    { billOfLading: 'COSU2026072203', bookingRef: 'BK-NGP-003', status: 'Booked', cargoType: 'Textiles', cargoWeight: 35000, cargoValue: 2100000, cargoDesc: 'Ready-made garments and fabrics', hsCode: '6203', vesselId: vessels[1].id, originPortId: ports[4].id, destPortId: ports[23].id, departureDate: new Date(now + 2 * 86400000), etd: new Date(now + 2 * 86400000), eta: new Date(now + 12 * 86400000), transitDays: 10, freightCost: 18000, currency: 'USD', shipper: 'Ningbo Textile Co. Ltd', consignee: 'Mombasa Trading House', notifyParty: 'Mombasa Trading House', forwarder: 'COSCO Forwarding', agent: 'Kenya Customs Agent', incoterms: 'CIF', paymentTerms: 'T/T 30 days', freightTerms: 'Prepaid', containerCount: 22, totalTEU: 22, totalFEU: 0, weightUnit: 'KG', volumeCbm: 145, dangerousGoods: false, customsStatus: 'Pending', customsRef: null, priority: 'Standard', serviceLevel: 'FCL', insurancePolicy: null, insuranceValue: null, remarks: 'Seasonal garment shipment' },
    { billOfLading: 'EGLV2026071504', bookingRef: 'BK-SUE-004', status: 'In Transit', cargoType: 'Oil Products', cargoWeight: 85000, cargoValue: 34000000, cargoDesc: 'Crude oil and petroleum products', hsCode: '2709', vesselId: vessels[7].id, originPortId: ports[12].id, destPortId: ports[13].id, departureDate: new Date(now - 1 * 86400000), etd: new Date(now - 1 * 86400000), eta: new Date(now + 2 * 86400000), transitDays: 3, freightCost: 145000, currency: 'USD', shipper: 'Emirates National Oil', consignee: 'Saudi Aramco Logistics', notifyParty: 'Aramco Trading', forwarder: 'V Ships Oil Tankers', agent: 'Jeddah Customs Broker', incoterms: 'FOB', paymentTerms: 'Net 15', freightTerms: 'Collect', containerCount: 0, totalTEU: 0, totalFEU: 0, weightUnit: 'KG', volumeCbm: 105000, dangerousGoods: true, dgClass: 'Class 3', unNumber: 'UN1267', customsStatus: 'Cleared', customsRef: 'AE-2026-89210', clearedAt: new Date(now - 86400000), priority: 'Standard', serviceLevel: 'Break Bulk', insurancePolicy: 'PETRO-2026-1234', insuranceValue: 35000000, remarks: 'Requires temperature monitoring - flammable cargo' },
    { billOfLading: 'ONEL2026071005', bookingRef: 'BK-TKO-005', status: 'In Transit', cargoType: 'Automobiles', cargoWeight: 42000, cargoValue: 8900000, cargoDesc: 'Passenger vehicles and automotive parts', hsCode: '8703', vesselId: vessels[6].id, originPortId: ports[16].id, destPortId: ports[10].id, departureDate: new Date(now - 8 * 86400000), etd: new Date(now - 8 * 86400000), eta: new Date(now + 4 * 86400000), transitDays: 12, freightCost: 78000, currency: 'USD', shipper: 'Toyota Motor Corp', consignee: 'LA Auto Distributors Inc', notifyParty: 'LA Auto Distributors Inc', forwarder: 'ONE Agency Japan', agent: 'US Customs Broker LA', incoterms: 'CIF', paymentTerms: 'L/C 60 days', freightTerms: 'Prepaid', containerCount: 0, totalTEU: 0, totalFEU: 0, weightUnit: 'KG', volumeCbm: 6800, dangerousGoods: false, customsStatus: 'Pending', customsRef: null, priority: 'Priority', serviceLevel: 'Ro-Ro', insurancePolicy: 'AUTO-2026-5678', insuranceValue: 9200000, remarks: 'Premium vehicle shipment - dealer delivery deadline' },
    { billOfLading: 'HLCU2026071206', bookingRef: 'BK-HAM-006', status: 'Arrived', cargoType: 'Chemicals', cargoWeight: 32000, cargoValue: 5600000, cargoDesc: 'Industrial chemicals and solvents', hsCode: '3824', vesselId: vessels[11].id, originPortId: ports[19].id, destPortId: ports[8].id, departureDate: new Date(now - 12 * 86400000), etd: new Date(now - 12 * 86400000), arrivalDate: new Date(now - 6 * 86400000), eta: new Date(now - 6 * 86400000), transitDays: 6, freightCost: 32000, currency: 'USD', shipper: 'Piraeus Chemicals SA', consignee: 'Hamburg Chemie GmbH', notifyParty: 'Hamburg Chemie GmbH', forwarder: 'Hapag-Lloyd Forwarding', agent: 'Hamburg Customs Agent', incoterms: 'DDP', paymentTerms: 'Net 30', freightTerms: 'Prepaid', containerCount: 15, totalTEU: 24, totalFEU: 3, weightUnit: 'KG', volumeCbm: 48, dangerousGoods: true, dgClass: 'Class 9', unNumber: 'UN3082', customsStatus: 'Cleared', customsRef: 'DE-2026-65432', clearedAt: new Date(now - 5 * 86400000), inspectionRequired: true, inspectionDate: new Date(now - 5 * 86400000), priority: 'Standard', serviceLevel: 'FCL', insurancePolicy: 'CHEM-2026-9012', insuranceValue: 5800000, remarks: 'DG cargo - requires special handling at Hamburg' },
    { billOfLading: 'MSCU2026072507', bookingRef: 'BK-SIN-007', status: 'Booked', cargoType: 'Agricultural', cargoWeight: 67000, cargoValue: 1800000, cargoDesc: 'Grain and agricultural commodities', hsCode: '1001', vesselId: vessels[3].id, originPortId: ports[2].id, destPortId: ports[1].id, departureDate: new Date(now + 3 * 86400000), etd: new Date(now + 3 * 86400000), eta: new Date(now + 12 * 86400000), transitDays: 9, freightCost: 42000, currency: 'USD', shipper: 'Euro Grain Trading BV', consignee: 'Singapore Agri Corp', notifyParty: 'Singapore Agri Corp', forwarder: 'MSC Agency Rotterdam', agent: 'Singapore Customs', incoterms: 'CFR', paymentTerms: 'CAD', freightTerms: 'Prepaid', containerCount: 0, totalTEU: 0, totalFEU: 0, weightUnit: 'KG', volumeCbm: 89000, dangerousGoods: false, customsStatus: 'Pending', customsRef: null, priority: 'Standard', serviceLevel: 'Break Bulk', insurancePolicy: null, insuranceValue: null, certificateNo: 'PHYTO-NL-2026-111', remarks: 'Phytosanitary certificate required' },
    { billOfLading: 'BARU2026070808', bookingRef: 'BK-MUM-008', status: 'Delivered', cargoType: 'Pharmaceuticals', cargoWeight: 8500, cargoValue: 12500000, cargoDesc: 'Pharmaceutical products and medical supplies', hsCode: '3004', vesselId: vessels[14].id, originPortId: ports[12].id, destPortId: ports[14].id, departureDate: new Date(now - 15 * 86400000), etd: new Date(now - 15 * 86400000), arrivalDate: new Date(now - 5 * 86400000), eta: new Date(now - 5 * 86400000), transitDays: 10, freightCost: 95000, currency: 'USD', shipper: 'Dubai Pharma Industries', consignee: 'Mumbai Healthcare Ltd', notifyParty: 'Mumbai Healthcare Ltd', forwarder: 'Barcelona Bridge Agency', agent: 'Mumbai Customs Broker', incoterms: 'DDP', paymentTerms: 'L/C at sight', freightTerms: 'Prepaid', containerCount: 8, totalTEU: 12, totalFEU: 2, weightUnit: 'KG', volumeCbm: 32, temperatureCtrl: true, tempMin: 2, tempMax: 8, dangerousGoods: false, customsStatus: 'Cleared', customsRef: 'IN-2026-43219', clearedAt: new Date(now - 4 * 86400000), priority: 'Priority', serviceLevel: 'FCL', insurancePolicy: 'PHARMA-2026-3344', insuranceValue: 13000000, remarks: 'Temperature-controlled pharma shipment - cold chain required' },
    { billOfLading: 'OOCL2026072009', bookingRef: 'BK-SHA-009', status: 'In Transit', cargoType: 'Furniture', cargoWeight: 28000, cargoValue: 3200000, cargoDesc: 'Office and household furniture', hsCode: '9403', vesselId: vessels[5].id, originPortId: ports[0].id, destPortId: ports[21].id, departureDate: new Date(now - 7 * 86400000), etd: new Date(now - 7 * 86400000), eta: new Date(now + 3 * 86400000), transitDays: 10, freightCost: 22000, currency: 'USD', shipper: 'Shanghai Furniture Mfg', consignee: 'Sydney Home Decor Pty', notifyParty: 'Sydney Home Decor Pty', forwarder: 'COSCO Forwarding', agent: 'Sydney Customs Broker', incoterms: 'CIF', paymentTerms: 'T/T 30 days', freightTerms: 'Prepaid', containerCount: 16, totalTEU: 24, totalFEU: 4, weightUnit: 'KG', volumeCbm: 185, dangerousGoods: false, customsStatus: 'Pending', customsRef: null, priority: 'Standard', serviceLevel: 'FCL', insurancePolicy: 'FURN-2026-5566', insuranceValue: 3500000, remarks: 'Flat-pack furniture - easy handling' },
    { billOfLading: 'MAEU2026070510', bookingRef: 'BK-LAX-010', status: 'Delivered', cargoType: 'Frozen Goods', cargoWeight: 41000, cargoValue: 680000, cargoDesc: 'Frozen seafood and perishable goods', hsCode: '0306', vesselId: vessels[0].id, originPortId: ports[1].id, destPortId: ports[10].id, departureDate: new Date(now - 20 * 86400000), etd: new Date(now - 20 * 86400000), arrivalDate: new Date(now - 10 * 86400000), eta: new Date(now - 10 * 86400000), transitDays: 10, freightCost: 55000, currency: 'USD', shipper: 'Singapore Seafood Pte', consignee: 'Pacific Foods International', notifyParty: 'Pacific Foods International', forwarder: 'Kuehne + Nagel Singapore', agent: 'LA Customs Broker', incoterms: 'CIF', paymentTerms: 'Net 15', freightTerms: 'Prepaid', containerCount: 12, totalTEU: 18, totalFEU: 3, weightUnit: 'KG', volumeCbm: 62, temperatureCtrl: true, tempMin: -18, tempMax: -25, dangerousGoods: false, customsStatus: 'Cleared', customsRef: 'US-2026-77654', clearedAt: new Date(now - 9 * 86400000), inspectionRequired: true, inspectionDate: new Date(now - 9 * 86400000), priority: 'Express', serviceLevel: 'FCL', insurancePolicy: 'FOOD-2026-7788', insuranceValue: 720000, demurrage: 0, detention: 450, remarks: 'Reefer containers - frozen at -25°C' },
  ]

  console.log(`📦 Creating ${shipmentsData.length} enriched shipments...`)
  const shipments = await Promise.all(shipmentsData.map((s) => db.shipment.create({ data: s })))

  // ============================
  // CONTAINERS (enriched)
  // ============================
  const containersData: any[] = []
  let cIdx = 0
  for (const shipment of shipments) {
    const numC = shipment.containerCount || (3 + Math.floor(Math.random() * 6))
    for (let i = 0; i < numC; i++) {
      cIdx++
      const sizeRoll = Math.random()
      const size = sizeRoll > 0.35 ? '40FT' : '20FT'
      const isoType = size === '40FT' ? '40DRY' : '20DRY'
      const isReefer = shipment.temperatureCtrl && i < 3
      const statusMap: Record<string, string> = { 'Booked': 'Loaded', 'In Transit': 'In Transit', 'Arrived': 'Arrived', 'Delivered': 'Empty' }
      containersData.push({
        containerNo: `MSCU${String(765432 + cIdx).padStart(7, '0')}`,
        isoType: isReefer ? (size === '40FT' ? '40RF' : '20RF') : isoType,
        size,
        status: statusMap[shipment.status] || 'Empty',
        weight: 5000 + Math.random() * 22000,
        vesselId: ['Booked', 'In Transit'].includes(shipment.status) ? shipment.vesselId : undefined,
        shipmentId: shipment.id,
        originPort: ports.find((p) => p.id === shipment.originPortId)?.unlocode,
        destPort: ports.find((p) => p.id === shipment.destPortId)?.unlocode,
        owner: 'MSC Leasing',
        maxPayload: size === '40FT' ? 28500 : 21700,
        tareWeight: size === '40FT' ? 3750 : 2230,
        cubicCapacity: size === '40FT' ? 67.3 : 33.1,
        sealNo: `MS${String(100000 + cIdx).padStart(7, '0')}`,
        sealType: 'Bolt',
        lastInspection: new Date(now - 90 * 86400000),
        nextInspection: new Date(now + 275 * 86400000),
        temperature: isReefer ? (shipment.tempMin || -18) : null,
        humidity: isReefer ? 85 : null,
        isInYard: shipment.status === 'Delivered',
        freeDays: 7,
      })
    }
  }

  console.log(`📦 Creating ${containersData.length} enriched containers...`)
  await db.container.createMany({ data: containersData })

  // ============================
  // SHIPMENT DOCUMENTS
  // ============================
  const docTypes = ['BOL', 'Commercial Invoice', 'Packing List', 'Customs Declaration', 'Certificate of Origin', 'Insurance Certificate']
  const documentsData: any[] = []
  for (const shipment of shipments) {
    const numDocs = 4 + Math.floor(Math.random() * 3)
    for (let i = 0; i < numDocs; i++) {
      documentsData.push({
        shipmentId: shipment.id,
        vesselId: shipment.vesselId,
        docType: docTypes[i % docTypes.length],
        docName: `${docTypes[i % docTypes.length]} - ${shipment.billOfLading || shipment.bookingRef}`,
        docRef: `${shipment.billOfLading?.substring(0, 8) || shipment.bookingRef}-DOC${i + 1}`,
        status: i === 0 ? 'Approved' : ['Approved', 'Pending', 'Pending'][Math.floor(Math.random() * 3)],
        issuedBy: shipment.shipper || 'Unknown',
        issuedAt: new Date((shipment.departureDate?.getTime() || now) - (i + 1) * 86400000),
        fileFormat: 'PDF',
        fileSize: 150000 + Math.floor(Math.random() * 850000),
      })
    }
  }

  console.log(`📄 Creating ${documentsData.length} shipment documents...`)
  await db.shipmentDocument.createMany({ data: documentsData })

  // ============================
  // SHIPMENT EVENTS (timeline)
  // ============================
  const eventsData: any[] = []
  const eventTemplates: Record<string, Array<{ type: string; desc: string }>> = {
    'Booked': [
      { type: 'Booked', desc: 'Shipment booking confirmed' },
      { type: 'CustomsFiled', desc: 'Export customs declaration filed' },
      { type: 'GateIn', desc: 'Container gated in at origin terminal' },
    ],
    'In Transit': [
      { type: 'Booked', desc: 'Shipment booking confirmed' },
      { type: 'CustomsFiled', desc: 'Export customs declaration filed' },
      { type: 'GateIn', desc: 'Container gated in at origin terminal' },
      { type: 'Loaded', desc: 'Container loaded aboard vessel' },
      { type: 'Departed', desc: 'Vessel departed origin port' },
      { type: 'AtSea', desc: 'Vessel in transit at sea' },
    ],
    'Arrived': [
      { type: 'Booked', desc: 'Shipment booking confirmed' },
      { type: 'Loaded', desc: 'Container loaded aboard vessel' },
      { type: 'Departed', desc: 'Vessel departed origin port' },
      { type: 'AtSea', desc: 'Vessel in transit at sea' },
      { type: 'Arrived', desc: 'Vessel arrived at destination port' },
      { type: 'Discharging', desc: 'Container discharging in progress' },
    ],
    'Delivered': [
      { type: 'Booked', desc: 'Shipment booking confirmed' },
      { type: 'Departed', desc: 'Vessel departed origin port' },
      { type: 'AtSea', desc: 'Vessel in transit at sea' },
      { type: 'Arrived', desc: 'Vessel arrived at destination port' },
      { type: 'Discharging', desc: 'Container discharging in progress' },
      { type: 'GateOut', desc: 'Container gated out of terminal' },
      { type: 'Delivered', desc: 'Cargo delivered to consignee' },
    ],
  }

  for (const shipment of shipments) {
    const templates = eventTemplates[shipment.status] || eventTemplates['Booked']
    for (let i = 0; i < templates.length; i++) {
      const evt = templates[i]
      const originPort = ports.find((p) => p.id === shipment.originPortId)
      const destPort = ports.find((p) => p.id === shipment.destPortId)
      const vessel = vessels.find((v) => v.id === shipment.vesselId)

      let location = originPort?.name || 'Unknown'
      let countryCode = originPort?.countryCode
      let lat = originPort?.latitude
      let lon = originPort?.longitude

      if (i >= 3) {
        location = destPort?.name || 'Unknown'
        countryCode = destPort?.countryCode
        lat = destPort?.latitude
        lon = destPort?.longitude
      }
      if (evt.type === 'AtSea') {
        location = 'At Sea'
        countryCode = null
        lat = null; lon = null
      }

      eventsData.push({
        shipmentId: shipment.id,
        eventType: evt.type,
        eventDesc: evt.desc,
        location,
        countryCode,
        latitude: lat,
        longitude: lon,
        vesselName: vessel?.name,
        performedBy: i < 2 ? shipment.shipper : i >= templates.length - 2 ? shipment.consignee : 'Port Authority',
        createdAt: new Date((shipment.departureDate?.getTime() || now) + i * 86400000 * (shipment.transitDays || 7) / templates.length),
      })
    }
  }

  console.log(`📋 Creating ${eventsData.length} shipment events...`)
  await db.shipmentEvent.createMany({ data: eventsData })

  // ============================
  // VESSEL ARRIVALS & DEPARTURES (enriched)
  // ============================
  const arrivals = [
    { vesselId: vessels[4].id, portId: ports[1].id, arrivalAt: new Date(now - 6 * 3600000), purpose: 'Discharging', berth: 'T4-S12', pilotName: 'Capt. Ahmed', agent: 'PSA Terminal', cargoDesc: 'Electronics, Textiles', dischargeTonnage: 8500, stayHours: 18 },
    { vesselId: vessels[12].id, portId: ports[20].id, arrivalAt: new Date(now - 12 * 3600000), purpose: 'Loading', berth: 'CT-3', pilotName: 'Capt. Santos', agent: 'Rio Port Ops', cargoDesc: 'Iron Ore', loadTonnage: 52000, stayHours: 36 },
    { vesselId: vessels[6].id, portId: ports[16].id, arrivalAt: new Date(now - 2 * 86400000), purpose: 'Discharging', berth: 'CB-05', pilotName: 'Capt. Tanaka', agent: 'Tokyo Customs', cargoDesc: 'Empty containers', dischargeTonnage: 0, stayHours: 24 },
    { vesselId: vessels[10].id, portId: ports[0].id, arrivalAt: new Date(now - 4 * 86400000), purpose: 'Bunkering', berth: 'BL-2', pilotName: 'Capt. Chen', agent: 'Shanghai Bunkering', cargoDesc: 'VLSFO supply', stayHours: 12 },
    { vesselId: vessels[13].id, portId: ports[23].id, arrivalAt: new Date(now - 3 * 86400000), purpose: 'Discharging', berth: 'MB-1', pilotName: 'Capt. Omondi', agent: 'KPA Operations', cargoDesc: 'General cargo', dischargeTonnage: 12000, stayHours: 48 },
  ]

  const departures = [
    { vesselId: vessels[4].id, portId: ports[1].id, departedAt: new Date(now - 2 * 3600000), destination: 'CNSHA', berth: 'T4-S12', nextPortETA: new Date(now + 5 * 86400000), draft: 13.2, cargoOnboard: 'Machinery, Electronics' },
    { vesselId: vessels[10].id, portId: ports[0].id, departedAt: new Date(now - 1 * 86400000), destination: 'JPTYO', berth: 'BL-2', nextPortETA: new Date(now + 3 * 86400000), draft: 12.8, cargoOnboard: 'Chemicals, Textiles' },
    { vesselId: vessels[9].id, portId: ports[20].id, departedAt: new Date(now - 5 * 86400000), destination: 'INBOM', berth: 'CT-3', nextPortETA: new Date(now + 7 * 86400000), draft: 14.0, cargoOnboard: 'Iron Ore, Steel' },
  ]

  console.log(`🔴 Creating ${arrivals.length} enriched vessel arrivals...`)
  await db.vesselArrival.createMany({ data: arrivals })
  console.log(`🟢 Creating ${departures.length} enriched vessel departures...`)
  await db.vesselDeparture.createMany({ data: departures })

  // ============================
  // TRADE DATA (enriched)
  // ============================
  const countryNames: Record<string, string> = { CN: 'China', US: 'United States', SG: 'Singapore', DE: 'Germany', JP: 'Japan', KR: 'South Korea', AU: 'Australia', IN: 'India', AE: 'United Arab Emirates', SA: 'Saudi Arabia', BR: 'Brazil', NG: 'Nigeria', GB: 'United Kingdom', NL: 'Netherlands', MY: 'Malaysia' }
  const tradeData = [
    { reporterCode: 'CN', reporterName: 'China', partnerCode: 'US', partnerName: 'United States', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '8542', commodityChapter: '85', commodityDesc: 'Electronic integrated circuits', grossWeightKg: 45800000, netWeightKg: 44200000, tradeValueUsd: 1250000000, quantity: 12500000, qtyUnit: 'number', unitValueUsd: 100, transportMode: 'Sea', vesselType: 'Container', estimatedVoyages: 650, co2EmissionsT: 285000, freightRateUsd: 0.042, transshipment: false, tradeRoute: 'Trans-Pacific' },
    { reporterCode: 'CN', reporterName: 'China', partnerCode: 'US', partnerName: 'United States', year: 2025, month: 6, tradeFlow: 'Import', commodityCode: '2709', commodityChapter: '27', commodityDesc: 'Petroleum oils', grossWeightKg: 85000000, netWeightKg: 83500000, tradeValueUsd: 420000000, quantity: 85000000, qtyUnit: 'kg', unitValueUsd: 4.94, transportMode: 'Sea', vesselType: 'Tanker', estimatedVoyages: 95, co2EmissionsT: 420000, freightRateUsd: 0.008, transshipment: false, tradeRoute: 'Trans-Pacific' },
    { reporterCode: 'CN', reporterName: 'China', partnerCode: 'SG', partnerName: 'Singapore', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '8471', commodityChapter: '84', commodityDesc: 'Automatic data processing machines', grossWeightKg: 12200000, netWeightKg: 11500000, tradeValueUsd: 890000000, quantity: 3200000, qtyUnit: 'number', unitValueUsd: 278, transportMode: 'Sea', vesselType: 'Container', estimatedVoyages: 145, co2EmissionsT: 42000, freightRateUsd: 0.035, transshipment: false, tradeRoute: 'Intra-Asia' },
    { reporterCode: 'DE', reporterName: 'Germany', partnerCode: 'CN', partnerName: 'China', year: 2025, month: 6, tradeFlow: 'Import', commodityCode: '8703', commodityChapter: '87', commodityDesc: 'Motor cars and vehicles', grossWeightKg: 23500000, netWeightKg: 22800000, tradeValueUsd: 1850000000, quantity: 580000, qtyUnit: 'number', unitValueUsd: 3190, transportMode: 'Sea', vesselType: 'Ro-Ro', estimatedVoyages: 180, co2EmissionsT: 68000, freightRateUsd: 0.065, transshipment: false, tradeRoute: 'Asia-Europe' },
    { reporterCode: 'DE', reporterName: 'Germany', partnerCode: 'US', partnerName: 'United States', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '8412', commodityChapter: '84', commodityDesc: 'Other engines and motors', grossWeightKg: 8900000, netWeightKg: 8650000, tradeValueUsd: 920000000, quantity: 2100000, qtyUnit: 'number', unitValueUsd: 438, transportMode: 'Sea', vesselType: 'Container', estimatedVoyages: 85, co2EmissionsT: 28000, freightRateUsd: 0.055, transshipment: false, tradeRoute: 'Trans-Atlantic' },
    { reporterCode: 'JP', reporterName: 'Japan', partnerCode: 'CN', partnerName: 'China', year: 2025, month: 6, tradeFlow: 'Import', commodityCode: '3004', commodityChapter: '30', commodityDesc: 'Medicaments', grossWeightKg: 5600000, netWeightKg: 5200000, tradeValueUsd: 680000000, quantity: 1800000, qtyUnit: 'kg', unitValueUsd: 377, transportMode: 'Sea', vesselType: 'Container', estimatedVoyages: 55, co2EmissionsT: 18000, freightRateUsd: 0.048, transshipment: false, tradeRoute: 'Intra-Asia' },
    { reporterCode: 'JP', reporterName: 'Japan', partnerCode: 'US', partnerName: 'United States', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '8703', commodityChapter: '87', commodityDesc: 'Motor cars', grossWeightKg: 62000000, netWeightKg: 59800000, tradeValueUsd: 5200000000, quantity: 1500000, qtyUnit: 'number', unitValueUsd: 3467, transportMode: 'Sea', vesselType: 'Ro-Ro', estimatedVoyages: 420, co2EmissionsT: 145000, freightRateUsd: 0.058, transshipment: false, tradeRoute: 'Trans-Pacific' },
    { reporterCode: 'KR', reporterName: 'South Korea', partnerCode: 'CN', partnerName: 'China', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '8542', commodityChapter: '85', commodityDesc: 'Semiconductor devices', grossWeightKg: 18500000, netWeightKg: 18200000, tradeValueUsd: 2100000000, quantity: 8500000, qtyUnit: 'number', unitValueUsd: 247, transportMode: 'Sea', vesselType: 'Container', estimatedVoyages: 210, co2EmissionsT: 72000, freightRateUsd: 0.038, transshipment: false, tradeRoute: 'Intra-Asia' },
    { reporterCode: 'US', reporterName: 'United States', partnerCode: 'CN', partnerName: 'China', year: 2025, month: 6, tradeFlow: 'Import', commodityCode: '9403', commodityChapter: '94', commodityDesc: 'Furniture and parts', grossWeightKg: 42000000, netWeightKg: 40500000, tradeValueUsd: 320000000, quantity: 15000000, qtyUnit: 'kg', unitValueUsd: 7.9, transportMode: 'Sea', vesselType: 'Container', estimatedVoyages: 380, co2EmissionsT: 132000, freightRateUsd: 0.042, transshipment: false, tradeRoute: 'Trans-Pacific' },
    { reporterCode: 'US', reporterName: 'United States', partnerCode: 'SA', partnerName: 'Saudi Arabia', year: 2025, month: 6, tradeFlow: 'Import', commodityCode: '2709', commodityChapter: '27', commodityDesc: 'Crude petroleum oil', grossWeightKg: 180000000, netWeightKg: 178000000, tradeValueUsd: 8900000000, quantity: 180000000, qtyUnit: 'kg', unitValueUsd: 50, transportMode: 'Sea', vesselType: 'Tanker', estimatedVoyages: 210, co2EmissionsT: 920000, freightRateUsd: 0.005, transshipment: false, tradeRoute: 'Middle East-Americas' },
    { reporterCode: 'AE', reporterName: 'UAE', partnerCode: 'IN', partnerName: 'India', year: 2025, month: 6, tradeFlow: 'Import', commodityCode: '1001', commodityChapter: '10', commodityDesc: 'Wheat and meslin', grossWeightKg: 28000000, netWeightKg: 27500000, tradeValueUsd: 78000000, quantity: 28000000, qtyUnit: 'kg', unitValueUsd: 2.79, transportMode: 'Sea', vesselType: 'Bulk', estimatedVoyages: 35, co2EmissionsT: 15000, freightRateUsd: 0.012, transshipment: false, tradeRoute: 'Intra-Asia' },
    { reporterCode: 'IN', reporterName: 'India', partnerCode: 'AE', partnerName: 'UAE', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '2709', commodityChapter: '27', commodityDesc: 'Petroleum oils', grossWeightKg: 65000000, netWeightKg: 64000000, tradeValueUsd: 4500000000, quantity: 65000000, qtyUnit: 'kg', unitValueUsd: 69.23, transportMode: 'Sea', vesselType: 'Tanker', estimatedVoyages: 78, co2EmissionsT: 350000, freightRateUsd: 0.007, transshipment: false, tradeRoute: 'Intra-Asia' },
    { reporterCode: 'AU', reporterName: 'Australia', partnerCode: 'CN', partnerName: 'China', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '2601', commodityChapter: '26', commodityDesc: 'Iron ores and concentrates', grossWeightKg: 850000000, netWeightKg: 845000000, tradeValueUsd: 68000000000, quantity: 850000000, qtyUnit: 'kg', unitValueUsd: 80, transportMode: 'Sea', vesselType: 'Bulk', estimatedVoyages: 1050, co2EmissionsT: 4500000, freightRateUsd: 0.004, transshipment: false, tradeRoute: 'Intra-Asia' },
    { reporterCode: 'BR', reporterName: 'Brazil', partnerCode: 'CN', partnerName: 'China', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '7204', commodityChapter: '72', commodityDesc: 'Iron and steel scrap', grossWeightKg: 32000000, netWeightKg: 31500000, tradeValueUsd: 95000000, quantity: 32000000, qtyUnit: 'kg', unitValueUsd: 2.97, transportMode: 'Sea', vesselType: 'Bulk', estimatedVoyages: 42, co2EmissionsT: 18000, freightRateUsd: 0.015, transshipment: false, tradeRoute: 'South America-Asia' },
    { reporterCode: 'NG', reporterName: 'Nigeria', partnerCode: 'IN', partnerName: 'India', year: 2025, month: 6, tradeFlow: 'Export', commodityCode: '2709', commodityChapter: '27', commodityDesc: 'Crude petroleum', grossWeightKg: 42000000, netWeightKg: 41500000, tradeValueUsd: 2100000000, quantity: 42000000, qtyUnit: 'kg', unitValueUsd: 50, transportMode: 'Sea', vesselType: 'Tanker', estimatedVoyages: 52, co2EmissionsT: 225000, freightRateUsd: 0.006, transshipment: false, tradeRoute: 'West Africa-Asia' },
  ]

  console.log(`📊 Creating ${tradeData.length} enriched trade data records...`)
  await db.tradeData.createMany({ data: tradeData })

  console.log('\n✅ Enhanced database seeded successfully!')
  console.log(`   🚢 Ports: ${ports.length}`)
  console.log(`   ⚓ Vessels: ${vessels.length}`)
  console.log(`   📦 Shipments: ${shipments.length}`)
  console.log(`   📦 Containers: ${containersData.length}`)
  console.log(`   📄 Documents: ${documentsData.length}`)
  console.log(`   📋 Events: ${eventsData.length}`)
  console.log(`   📊 Trade Records: ${tradeData.length}`)
}

seedRichMaritimeData()
  .catch((e) => { console.error('❌ Seed failed:', e); process.exit(1) })
  .finally(() => process.exit(0))
